# ABOUTME: Download helper CLI providing wget/aria2c commands for sensor blob downloads
# ABOUTME: MVP version - shows download commands; full automation coming in Phase 2

from __future__ import annotations

import os
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.syntax import Syntax

from nuplan.cli.dataset_utils import S3_BASE_URL, get_sensor_blob_zip_name


cli = typer.Typer()
console = Console()

NUPLAN_DATA_ROOT = Path(os.getenv("NUPLAN_DATA_ROOT", "/data/sets/nuplan/"))


@cli.command()
def mini(
    camera: str = typer.Option(None, help="Camera sets to download (e.g., '0,1,2' or '0')"),
    lidar: str = typer.Option(None, help="LiDAR sets to download (e.g., '0,1' or '0')"),
    skip_db: bool = typer.Option(False, help="Skip database files"),
    skip_maps: bool = typer.Option(False, help="Skip map files"),
    data_root: Path = typer.Option(NUPLAN_DATA_ROOT, help="Dataset root directory"),
) -> None:
    """
    Generate download commands for mini dataset with selective sensor filtering.

    Example:
        nuplan_cli download mini --camera=0 --lidar=0
        nuplan_cli download mini --camera=0,1,2 --lidar=0,1
    """
    console.print("\n[bold cyan]nuPlan Mini Dataset Download Helper[/bold cyan]\n")

    # Parse camera and lidar sets
    camera_sets = [int(x.strip()) for x in camera.split(",")] if camera else []
    lidar_sets = [int(x.strip()) for x in lidar.split(",")] if lidar else []

    # Validate indices
    for i in camera_sets:
        if not (0 <= i <= 7):
            console.print(f"[red]Error:[/red] Camera set must be 0-7, got {i}")
            raise typer.Exit(1)

    for i in lidar_sets:
        if not (0 <= i <= 8):
            console.print(f"[red]Error:[/red] LiDAR set must be 0-8, got {i}")
            raise typer.Exit(1)

    # Build download URLs
    urls = []

    if not skip_db:
        urls.append(f"{S3_BASE_URL}/nuplan-v1.1_mini.zip")  # Database (8 GB)

    if not skip_maps:
        urls.append(f"{S3_BASE_URL}/nuplan-maps-v1.1.zip")  # Maps (927 MB)

    # Add sensor blob URLs
    for i in camera_sets:
        zip_name = get_sensor_blob_zip_name("camera", i, "mini")
        urls.append(f"{S3_BASE_URL}/sensor_blobs/mini_set/{zip_name}")

    for i in lidar_sets:
        zip_name = get_sensor_blob_zip_name("lidar", i, "mini")
        urls.append(f"{S3_BASE_URL}/sensor_blobs/mini_set/{zip_name}")

    if not urls:
        console.print("[yellow]No files selected for download[/yellow]")
        console.print("Use --camera and/or --lidar to specify sensor sets\n")
        return

    # Calculate estimated size
    total_size_gb = 0
    if not skip_db:
        total_size_gb += 8
    if not skip_maps:
        total_size_gb += 1
    total_size_gb += len(camera_sets) * 350  # ~350 GB per camera set
    total_size_gb += len(lidar_sets) * 60  # ~60 GB per lidar set

    # Display summary
    console.print(f"[bold]Selected files:[/bold] {len(urls)}")
    console.print(f"[bold]Estimated size:[/bold] ~{total_size_gb} GB")
    console.print(f"[bold]Destination:[/bold] {data_root}\n")

    # Generate wget commands
    wget_script = f"""#!/bin/bash
# Generated by nuplan_cli download mini
# Destination: {data_root}

set -euo pipefail

cd "{data_root}"

# Download files with wget
"""

    for url in urls:
        filename = url.split("/")[-1]
        wget_script += f'echo "Downloading {filename}..."\n'
        wget_script += f'wget -c "{url}" -O "{filename}"\n\n'

    wget_script += "echo 'All downloads complete!'\n"

    # Generate aria2c commands (faster, parallel)
    aria2c_script = f"""#!/bin/bash
# Generated by nuplan_cli download mini (aria2c version - faster!)
# Destination: {data_root}

set -euo pipefail

cd "{data_root}"

# Create URL list file
cat > nuplan_urls.txt <<EOF
"""

    for url in urls:
        aria2c_script += f"{url}\n"

    aria2c_script += """EOF

# Download with aria2c (parallel, resume-capable)
aria2c \\
  --input-file=nuplan_urls.txt \\
  --continue=true \\
  --max-connection-per-server=16 \\
  --split=16 \\
  --min-split-size=4M \\
  --max-concurrent-downloads=2 \\
  --file-allocation=falloc \\
  --summary-interval=10

echo 'All downloads complete!'

# Extract zips
echo 'Extracting archives...'
for zip in *.zip; do
    echo "Extracting $zip..."
    unzip -n "$zip"
done

echo 'Setup complete!'
"""

    # Display scripts
    console.print(Panel(Syntax(wget_script, "bash", theme="monokai"), title="[bold green]Option 1: wget (simple)[/bold green]", border_style="green"))

    console.print()

    console.print(Panel(Syntax(aria2c_script, "bash", theme="monokai"), title="[bold cyan]Option 2: aria2c (faster, recommended)[/bold cyan]", border_style="cyan"))

    # Save scripts to files
    wget_file = data_root / "download_nuplan_wget.sh"
    aria2c_file = data_root / "download_nuplan_aria2c.sh"

    with open(wget_file, "w") as f:
        f.write(wget_script)
    wget_file.chmod(0o755)

    with open(aria2c_file, "w") as f:
        f.write(aria2c_script)
    aria2c_file.chmod(0o755)

    console.print(f"\n[bold]Scripts saved:[/bold]")
    console.print(f"  wget:   {wget_file}")
    console.print(f"  aria2c: {aria2c_file}")

    console.print("\n[bold]To download:[/bold]")
    console.print(f"  {aria2c_file}")
    console.print("\n[dim]Tip: aria2c is much faster for large files. Install with: sudo apt install aria2[/dim]\n")


@cli.command()
def full(
    maps_only: bool = typer.Option(False, help="Download only map files"),
    data_root: Path = typer.Option(NUPLAN_DATA_ROOT, help="Dataset root directory"),
) -> None:
    """
    Generate download commands for full dataset (~10TB).

    Example:
        nuplan_cli download full --maps-only
    """
    console.print("\n[bold red]Warning: Full dataset is ~10TB![/bold red]")
    console.print("This will take many hours to download.\n")

    if not maps_only:
        console.print("[yellow]Full dataset download not yet implemented.[/yellow]")
        console.print("Please use the bash script for now:\n")
        console.print("  ./nuplan_mini_dl.sh\n")
        console.print("Or download maps only with: --maps-only\n")
        return

    # Maps only
    url = f"{S3_BASE_URL}/nuplan-maps-v1.1.zip"
    console.print(f"[bold]Downloading:[/bold] Maps (927 MB)")
    console.print(f"[bold]URL:[/bold] {url}")
    console.print(f"[bold]Destination:[/bold] {data_root}\n")

    console.print("[bold]Command:[/bold]")
    console.print(f'  wget -c "{url}" -P "{data_root}"\n')


if __name__ == "__main__":
    cli()
